-- 09.83 — Seed 21 video themes from the theme-videos Supabase Storage bucket.
--
-- Source videos were curated + uploaded in 09.79 / 09.79.1 (see
-- scripts/process-theme-videos.ts). Names + categories + recommended text
-- colors were assigned via visual inspection of each video's poster JPG.
--
-- order_index 100..120 — video themes group together AFTER the static themes
-- (Prompt 04 reaches order_index 46, leaving room for category growth in
-- the 50–99 band before the video block).

insert into public.themes
  (name, category, background_type, background_value, recommended_text_color, order_index)
values
  ('Money Roll', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-5849600.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-5849600.jpg"}'::jsonb, '#ffffff', 100),
  ('Watercolor Bloom', 'trending', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-6546653.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-6546653.jpg"}'::jsonb, '#ffffff', 101),
  ('Pastel Craft', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-6943215.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-6943215.jpg"}'::jsonb, '#1a1a1a', 102),
  ('Paper Bud', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-6943221.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-6943221.jpg"}'::jsonb, '#1a1a1a', 103),
  ('Cotton Smoke', 'trending', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-7077358.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-7077358.jpg"}'::jsonb, '#ffffff', 104),
  ('Yellow Peace', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-8819028.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-8819028.jpg"}'::jsonb, '#1a1a1a', 105),
  ('Galaxy Stream', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-9860821.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-9860821.jpg"}'::jsonb, '#ffffff', 106),
  ('Ink Drip', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-10577135.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-10577135.jpg"}'::jsonb, '#1a1a1a', 107),
  ('Liquid Marble', 'trending', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-11499368.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-11499368.jpg"}'::jsonb, '#ffffff', 108),
  ('Starfield', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-12103118.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-12103118.jpg"}'::jsonb, '#ffffff', 109),
  ('Lava Lamp', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-12421291.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-12421291.jpg"}'::jsonb, '#1a1a1a', 110),
  ('Ember Glow', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-12802094.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-12802094.jpg"}'::jsonb, '#ffffff', 111),
  ('Magenta Aura', 'trending', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-12802144.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-12802144.jpg"}'::jsonb, '#ffffff', 112),
  ('Galaxy Core', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-12820534.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-12820534.jpg"}'::jsonb, '#ffffff', 113),
  ('Velvet Frame', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-13547658.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-13547658.jpg"}'::jsonb, '#ffffff', 114),
  ('Warm Velvet', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-13610558.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-13610558.jpg"}'::jsonb, '#ffffff', 115),
  ('Magenta Plasma', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-15054172.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-15054172.jpg"}'::jsonb, '#ffffff', 116),
  ('Bright Idea', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-16069880.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-16069880.jpg"}'::jsonb, '#ffffff', 117),
  ('Curious Faces', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-16093601.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-16093601.jpg"}'::jsonb, '#1a1a1a', 118),
  ('Doodle Shapes', 'fun', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-17348334.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-17348334.jpg"}'::jsonb, '#1a1a1a', 119),
  ('Neon Sketches', 'dark', 'video', '{"type":"video","src":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/videos/pexels-18550659.mp4","poster":"https://whvzgmqczipqxzsuinfq.supabase.co/storage/v1/object/public/theme-videos/posters/pexels-18550659.jpg"}'::jsonb, '#ffffff', 120);
